name: Deploy ColdKar Mexico
on:
  push:
    branches:
      - main  # Asegúrate que tu rama se llame main

jobs:
  web-deploy:
    name: 🚀 Deploy via FTP
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: public_html/
          protocol: ftp
          port: 21
          # Esta opción evita que el servidor bloquee la conexión por demasiados intentos
          timeout: 60000